Auth:
  Username: "3210561027"
  Password: "3210561027"
Client:
  Name: Client-NAT
  PublicServerAddr: pogf.com.cn
  TunnelServerAddr: pogf.com.cn:8008
  ControllerAddr: pogf.com.cn:8080
  LocalServerAddr: 0.0.0.0:8080
