Auth:
  Username: "3210561027"
  Password: "00000000"
Client:
  Name: Client-NAT
  PublicServerAddr: 127.0.0.1
  TunnelServerAddr: 127.0.0.1:8008
  ControllerAddr: 127.0.0.1:8080
  LocalServerAddr: 0.0.0.0:8000
