Server:
  Name: "Server-NAT"
  ControllerAddr: "0.0.0.0:8007"
  TunnelAddr: "0.0.0.0:8008"
  VisitPort:
    - 60000
    - 60001
    - 60002
    - 60003
  TaskQueueNum: 4
  TaskQueueBuff: 32
  MaxTCPConnNum: 4
  MaxConnNum: 256
  LogFilename: "server.log"
  StartAuth: true
Database:
  Username: "root"
  Password: "123456"
  Host: "127.0.0.1:3309"
  DBName: "NAT"
